In [0]:
import numpy.polynomial.legendre as leg

In [0]:
###1. Exception handling

In [9]:
while True:
	try:
		a = int(input("Enter a number to be divided by 5: "))
		result = 5/a
	except:
		print("ERROR. Please enter non-zero number")
	else:
		print("Computation is: ",result)
		break

Enter a number to be divided by 5: 0
ERROR. Please enter non-zero number
Enter a number to be divided by 5: 5
Computation is:  1.0


In [0]:
###2. Print all permutations

In [11]:
x=["Americans","Indians"]
y=["Play", "watch"]
z=["Baseball","cricket"]
for i in range(len(x)):
	for j in range(len(y)):
		for k in range(len(z)):
			print(x[i],y[j],z[k])

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [0]:
###3. input vector-> geometric progression output matrix

In [14]:
output = leg.legvander((1, 3, 5, 7), 2) 
  
print(output)

[[ 1.  1.  1.]
 [ 1.  3. 13.]
 [ 1.  5. 37.]
 [ 1.  7. 73.]]
