In [0]:
import numpy as np
import numpy.polynomial.legendre as leg

Moving averages

In [0]:
input_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N=3
cumulative_sum, moving_average = [0], []
for i ,x in enumerate(input_list,1):
  cumulative_sum.append(cumulative_sum[i-1]+x)
  if i>=N:
    moving_aver = (cumulative_sum[i] - cumulative_sum[i-N])/N
    moving_average.append("{:.2f}".format(moving_aver))


In [30]:
print(moving_average)

['5.00', '4.67', '5.67', '6.67', '9.67', '28.67', '49.33', '72.67', '84.00', '93.33', '116.33']


Vandermonde matrix

In [32]:
output = leg.legvander((1, 3, 5, 7), 2) 
  
print(output)

[[ 1.  1.  1.]
 [ 1.  3. 13.]
 [ 1.  5. 37.]
 [ 1.  7. 73.]]
